name: Publish Docker image, nodejs lts

on:
  push:
    branches:
      - master
    paths:
      - 'node-lts/**'
      - .github/workflows/node-lts.yml

env:
  REGISTRY: docker.io
  IMAGE_NAME: "${{ secrets.DOCKER_USERNAME }}/node-lts"
  TAG: "6.0"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
              ${{ env.TAG }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: "./node-lts/"
          build-args: |
            TARGETPLATFORM=linux/amd64
            BUILDPLATFORM=linux/amd64
            BASE_IMAGE=node:lts
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
